terranUnits = {
    'scv': 'SCV',
    'banshee': "Banshee",
    'battlecruiser': 'Battle Cruiser',
    'cyclone': 'Cyclone',
    'ghost': 'Ghost',
    'hellbat': 'Hellbat',
    'hellion': 'Hellion',
    'liberator': 'Liberator',
    'marauder': 'Marauder',
    'marine': 'Marine',
    'medivac': 'Medivac',
    'mule': 'Mule',
    'raven': 'Raven',
    'reaper': 'Reaper',
    'siegetank': 'Siege Tank',
    'thor': 'Thor',
    'viking': 'Viking',
    'widowmine': 'Widow Mine'
}

terranBuildings = {
    'armory': 'Armory',
    'barracks': 'Barracks',
    'bunker': 'Bunker', 
    'commandcenter': 'Command Center',
    'engineeringbay': 'Engineering Bay',
    'factory': 'Factory',
    'fusioncore': 'Fusion Core',
    'ghostacademy': 'Ghost Academy',
    'missleturret': 'Missile Turret',
    'orbitalcommand': 'Orbital Command',
    'reactor': 'Reactor',
    'refinery': 'Refinery',
    'sensortower': 'Sensor Tower',
    'starport': 'Star Port',
    'supplydepot': 'Supply Depot', 
    'techlab': 'Tech Lab',
    'planetaryfortress': 'Planetary Fortress'
}

terranUpgrades = {
    'researchcombatshield': 'Combat Shield',
    'researchinfernalpreigniter': 'Infernal Pre-Igniter',
    'researchstimpack': 'Stimpack',
    'researchcyclonelockondamageupgrade': 'Mag-Field Accelerator',
    'researchcloakingfield': 'Cloaking Field',
    'upgradevehicleweapons1': 'Vehicle Weapons +1',
    'researchdrillingclaws': 'Drilling Claws',
    'researchsmartservos': 'Smart Servos',
    'researchcorvidreactor': 'Corvid Reactor',
    'researchconcussiveshells': 'Concussive Shells',
    'researchterranvehicleandshiparmorslevel1': 'Vehicle and Ship Armor +1',
    'upgradeterraninfantryweapons1': 'Infantry Weapons +1',
    'upgradeterraninfantryarmor1': 'Infantry Armor +1',
    'upgradevehicleweapons2': 'Vehicle Weapons 2', 
    'researchbansheespeed': 'Hyperflight Rotors',
    'researchpersonalcloaking': 'Personal Cloaking',
    'researchmedivacincreasespeedboost': 'Rapid Reignition System',
    'researchweaponrefit': 'Weapon Refit',
    'researchbehemothreactor': 'Behemoth Reactor',
    'researchenhancedshockwaves': 'Enhanced Shockwaves',
    'upgradeterraninfantryweapons2': 'Infantry Weapons +2',
    'upgradeterraninfantryarmor2': 'Infantry Armor +2',
    'researchhisecautotracking': 'Hi-Sec Auto Tracking',
    'upgradestructurearmor': 'Neosteel Armor',
    'researchterranvehicleandshiparmorslevel2': 'Vehicle and Ship Armor +2',
    'upgradeshipweapons1': 'Ship Weapons +1',
    'upgradevehicleweapons3': 'Vehicle Weapons +3',
    'upgradeterraninfantryweapons3': 'Infantry Weapons +3',
    'upgradeterraninfantryarmor3': 'Infantry Armor +3',
    'upgradeshipweapons2': 'Ship Weapons +2',
    'researchterranvehicleandshiparmorslevel3': 'Vehicle and Ship Armos +3',
    'upgradeshipweapons3': 'Ship Weapons +3'
}

protossUpgrades = {
    'upgradeairweapons1': 'Air Weapons +1',
    'upgradegroundweapons1': 'Ground Weapons +1',
    'upgradegroundarmor1': 'Ground Armor +1',
    'researchcharge': 'Charge',
    'upgradeairarmor1': 'Air Armor +1',
    'upgradegroundweapons2': 'Ground Weapons +2',
    'upgradegroundarmor2': 'Ground Armor +2',
    'researchpsistormtech': 'Psi Storm',
    'researchblink': 'Blink',
    'researchdarktemplarblinkupgrade': 'Dark Templar Blink',
    'researchwarpgate': 'Warp Gate',
    'researchadeptpiercingattack': 'Piercing Attacks',
    'researchextendedthermallance': 'Thermal Lance',
    'upgradegroundweapons3': 'Ground Weapons +3',
    'upgradegroundarmor3': 'Ground Armor +3',
    'researchanionpulsecrystals': 'Anion Pulse Crystals',
    'researchbosoniccore': 'Bosonic Core',
    'researchgravitysling': 'Gravity Sling',
    'upgradeshields1': 'Shields +1',
    'researchgraviticdrive': 'Gravitic Drive',
    'researchgraviticboosters': 'Gravitic boosters',
    'upgradeairweapons2': 'Air Weapons +2',
    'upgradeairarmor2': 'Air Armor +2',
    'upgradeshields2': 'Shields +2',
    'upgradeairweapons3': 'Air Weapons +3',
    'upgradeairarmor3': 'Air Armor +3',
    'upgradesshields3': 'Shields +3'
}

protossUnits = {
    'probe': 'Probe',
    'zealot': 'Zealot',
    'sentry': 'Sentry',
    'stalker': 'Stalker',
    'adept': 'Adept',
    'hightemplar': 'High Templar',
    'darktemplar': 'Dark Templar',
    'archon': 'Arhcon',
    'observer': 'Observer',
    'warpprism': 'Warp Prism',
    'immortal': 'Immortal',
    'colossus': 'Colossus',
    'disruptor': 'Disruptor',
    'phoenix': 'Phoenix',
    'voidray': 'Void Ray',
    'oracle': 'Oracle',
    'tempest': 'Tempest',
    'carrier': 'Carrier',
    'interceptor': 'Interceptor',
    'mothership': 'Mothership'
}

protossBuildings = {
    'nexus': 'Nexus',
    'pylon': 'Pylon',
    'assimilator': 'Assimilator',
    'gateway': 'Gateway',
    'forge': 'Forge',
    'photoncannon': 'Photon Cannon',
    'shieldbattery': 'Shield Battery',
    'warpgate': 'Warp Gate',
    'cyberneticscore': 'Cybernetics Core',
    'twilightcouncil': 'Twilight Council',
    'roboticsfacility': 'Robotics Facility',
    'stargate': 'Stargate',
    'templararchive': 'Templar Archives',
    'darkshrine': 'Dark Shrine',
    'roboticsbay': 'Robotics Bay',
    'fleetbeacon': 'Fleet Beacon'
}

zergUnits = {
    'drone': 'Drone',
    'queen': 'Queen',
    'zergling': 'Zergling',
    'baneling': 'Baneling',
    'roach': 'Roach',
    'ravager': 'Ravager',
    'hydralisk': 'Hydralisk',
    'lurker': 'Lurker',
    'infestor': 'Infestor',
    'swarmhost': 'Swarm Host',
    'ultralisk': 'Ultralisk',
    'overlord': 'Overlord',
    'overseer': 'Overseer',
    'mutalisk': 'Mutalisk',
    'corruptor': 'Corruptor',
    'viper': 'Viper',
    'broodlord': 'Broodlord',
    'spinecrawler': 'Spine Crawler',
    'sporecrawler': 'Spore Crawler',
}

zergBuildings = {
    'hatchery': 'Hatchery',
    'extractor': 'Extractor',
    'spawningpool': 'Spawning Pool',
    'evolutionchamber': 'Evolution Chamber',
    'spinecrawler': 'Spine Crawler',
    'sporecrawler': 'Spore Crawler',
    'roachwarren': 'Roach Warren',
    'banelingnest': 'Baneling Nest',
    'lair': 'Lair',
    'hydraliskden': 'Hydralisk Den',
    'infestationpit': 'Infestation Pit',
    'spire': 'Spire',
    'nydusnetwork': 'Nydus Network', 
    'hive': 'Hive',
    'ultraliskcavern': 'Ultralisk Cavern',
}

zergUpgrades = {
   
    'zergmeleeweaponslevel1': 'Melee Attacks +1',
    'zergmeleeweaponslevel2': 'Melee Attacks +2',
    'zergmeleeweaponslevel2': 'Melee Attacks +3',
    'zergmissileweaponslevel1': 'Missile Attacks +1',
    'zergmissileweaponslevel2': 'Missile Attacks +2',
    'zergmissileweaponslevel3': 'Missile Attacks +3',
    'zerggroundarmorslevel1': 'Ground Carapace +1',
    'zerggroundarmorslevel2': 'Ground Carapace +2',
    'zerggroundarmorslevel3': 'Ground Carapace +3',
    'zergflyerarmorslevel1': 'Flyer Carapace +1',
    'zergflyerarmorslevel2': 'Flyer Carapace +2',
    'zergflyerarmorslevel3': 'Flyer Carapace +3',
    'zergflyerweaponslevel1': 'Flyer Attacks +1',
    'zergflyerweaponslevel2': 'Flyer Attacks +2',
    'zergflyerweaponslevel3': 'Flyer Attacks +3',
    'zerglingmovementspeed': 'Metabolic Boost',
    'glialreconstitution': 'Glial reconstitution',
    'evlovegroovedspines': 'Grooved Spines',
    'infestorenergyupgrade': 'Pathogen Glands',
    'overlordspeed': 'Pneumatized Carapzce',
    'tunnelingclaws': 'Tunneling Claws',
    'evolvemuscularaugments': 'Muscular Augments',
    'zerglingattackspeed': 'Adrenal Glands',
    'burrow': 'Burrow',
    'lurkerrange': 'Seismic Spines',
    'chitinousplating': 'Chitinous Plating',
    'anabolicsynthesis': 'Anabolic Synthesis',
    'centrifugalhooks': 'Centrifugal Hooks',   
    'nerualparasite': 'Nerual Parasite',
    'adaptivetalons': 'Adaptive Talons'
}